services:
  test_server:
    build: ./test-server
    ports:
    - "5001:5001"
    networks:
      - api_gateway_network
  user_service:
    build: ./user-service
    ports:
    - "4000:4000"
    networks:
      - api_gateway_network
  # user_service_db:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_USER=admin
  #     # - POSTGRES_DB=citizix_db
  load_balancer:
    build: ./load-balancer 
    ports:
    - "8080:80"
    networks:
      - loadbalancing
      - api_gateway_network
    depends_on:
      - api_gateway
  api_gateway:
    build: ./api-gateway
    ports:
    - "9090:90"
    networks:
      - loadbalancing
      - api_gateway_network 
    depends_on:
      - user_service
      - test_server
      
networks:
  loadbalancing:
  api_gateway_network: